### ISSUE TITLE
config enhancements

### ISSUE THREAD

**Issue by Sylensky** [EtienneDx/RealEstate#37] opened 2021-09-20 22:17 UTC
Hi,
i was looking a long time for a plugin just like yours and finally there it is.
Previously all the stuff was handled manually which was a lot of work for staffs and it is completely free of it now thanks to you.

I do have some enhancements that you might consider on your way with the plugin:
- more configurable messages
- variable prefix selection
- selectable permissions

In addition keep up the good work!

**Comment by EtienneDx** [comment] 2022-01-14 15:23
Hey, for the message part, it should come with the next version (#36), and the issue is being monitored at #26.
By prefixes, do you mean the [RealEstate] prefix?

For the permissions, parts of it are done but I haven't have a good look at it in forever, so I'll try to look at it later.

**Comment by Sylensky** [comment] 2022-01-14 18:58
Yes i meant the [RealEstate] prefix.

**Comment by EtienneDx** [comment] 2022-01-15 08:49
Ok, I think the prefix is already included in the messages.yml file which is added in the next version. I’ll double check when I get home before closing this issue

**Comment by EtienneDx** [comment] 2022-03-07 10:40
Hey, I've double checked, the prefix is part of the config file already. For the permission part, another issue is already openned I believe

**Closed by EtienneDx** 2022-03-07 10:40 UTC
Labels: enhancement
