### ISSUE TITLE
Config.yml keeps resetting the sign header

### ISSUE THREAD

**Issue by pokemonrocks9** [EtienneDx/RealEstate#34] opened 2021-07-18 16:40 UTC
the sign header in config.yml keeps resetting. first to &6[RealEstate] then after a server reboot it changes to ?6[RealEstate]
this breaks the real estates on sale for some reason. may be an issue on 1.17.1 in particular

**Comment by EtienneDx** [comment] 2021-09-08 13:29
Thanks for reporting it, this issue is a duplicate of #28 but helped me pinpoint the problem

**Closed** 2021-09-08 13:29 UTC
Labels: duplicate
