### ISSUE TITLE
Admin sub-claims for rent and `re list` command issue

### ISSUE THREAD

**Issue by DmitryRendov** [EtienneDx/RealEstate#18] opened 2020-05-12 09:25 UTC
```
[12:20:28 INFO]: [RealEstate] transaction 0
[12:20:28 INFO]: I'm sorry, but there was an error performing this command.
[12:20:28 ERROR]: [RealEstate] [ACF] Exception in command: re list all
[12:20:39 ERROR]: [RealEstate] [ACF] java.lang.reflect.InvocationTargetException
[12:20:39 ERROR]: [RealEstate] [ACF]    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[12:20:39 ERROR]: [RealEstate] [ACF]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:20:39 ERROR]: [RealEstate] [ACF]    at java.lang.reflect.Method.invoke(Unknown Source)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.acf.RegisteredCommand.invoke(RegisteredCommand.java:154)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.acf.BaseCommand.execute(BaseCommand.java:513)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.acf.RootCommand.execute(RootCommand.java:99)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[12:20:39 ERROR]: [RealEstate] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:20:39 ERROR]: [RealEstate] [ACF]    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742)
[12:20:39 ERROR]: [RealEstate] [ACF]    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:704)
[12:20:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[12:20:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[12:20:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[12:20:39 ERROR]: [RealEstate] [ACF]    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[12:20:39 ERROR]: [RealEstate] [ACF]    at java.lang.Thread.run(Unknown Source)
[12:20:39 ERROR]: [RealEstate] [ACF] Caused by: java.lang.NullPointerException
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.Transactions.ClaimRent.msgInfo(ClaimRent.java:402)
[12:20:39 ERROR]: [RealEstate] [ACF]    at me.EtienneDx.RealEstate.RECommand.list(RECommand.java:132)
[12:20:39 ERROR]: [RealEstate] [ACF]    ... 16 more
```

**Comment by EtienneDx** [comment] 2020-05-12 16:11
I couldn't reproduce, could you provide more informations about when the bug happened, when was the claim created, when was the sign put up, etc?

**Comment by DmitryRendov** [comment] 2020-05-13 12:48
I used latest RE release from github and bare paper server with min plugins that are needed to run.
Then,
1. Create one big claim (doesnt matter user's or admin's)
2. Create one sub-claim inside
3. Make sub-claim for rent
4. Rent this claim by another test player
5. Type command /re list

Looks like **msgInfo** fires NullPointerException because of the GP dataStore.getClaim() returns nothing in case of sub-claims.

**Comment by EtienneDx** [comment] 2020-05-13 19:37
I'll look into it tomorrow, kinda busy tonight ^^

**Comment by EtienneDx** [comment] 2020-05-14 13:58
Alright, I confirm this to be a bug, it's due to GriefPrevention not returning subclaims when fetching them by ID.

It will be fixed in the next modified version release OR (if merged by RoboMWM) in the next GP version

**Closed by EtienneDx** 2020-05-14 13:58 UTC
